### ISSUE TITLE
Pyexasol crashed in Kubernete due to incorrectly identified as orphaned process

### ISSUE THREAD

**Issue by superoverflow** [badoo/pyexasol#12]
When running pyexasol inside a kubernete pod, pyexasol crashed as it incorrectly identified the process as an orphan. This behavior was introduced in commit 
> 39d8ae3688510f9c5f04465a0d4bf4591b73e478

Please see below for more details for the error:

```
RuntimeError: Current process is orphaned, ppid=1
at check_orphaned (/usr/local/lib/python3.6/site-packages/pyexasol/utils.py:120)
at handle_request (/usr/local/lib/python3.6/site-packages/pyexasol/http_transport.py:245)
at <module> (/usr/local/lib/python3.6/site-packages/pyexasol/__main__.py:43)

```

Below is the ps stack for the kube pod
```
$ kubectl exec my-pod -- ps -ef
UID        PID  PPID C STIME TTY          TIME CMD
root        1     0  0 22:07 ?        00:00:01 python some.py
root        8     1  2 22:07 ?        00:00:01 /usr/local/bin/python -m pyexasol http --host x.x.x.x --port yyyy --mode export
```

**Comment by wildraid** [comment]
Very interesting. Kubernetes must be introducing a lot of problems with different software, since pid=1 is special in Linux.

I'll research this issue and see what we can do.

In the meantime, you may go back to `0.3.29`.
```
pip install pyexasol==0.3.29
```

Thanks!

**Comment by wildraid** [comment]
As I thought, it causes problems with other software as well: https://blog.ghaiklor.com/avoid-running-nodejs-as-pid-1-under-docker-images-when-running-them-on-mesosphere-kubernetes-or-b7bd505657f9

**Comment by wildraid** [comment]
@superoverflow , please try version `0.3.32`. I hope it will help!

```
pip install pyexasol==0.3.32
```

**Comment by superoverflow** [comment]
@wildraid, thanks for the prompt help. I just double check the log. We dont have any orphan process errors for the past week! so I think it is safe to say it is all fixed 👍

**Comment by superoverflow** [comment]
No orphan proces error seeing for past 10 days
