### ISSUE TITLE
Ignore duplicates on import_from_iterable

### ISSUE THREAD

**Issue by kst83** [badoo/pyexasol#13]
Hello,

is there a way to ignore/not insert entries with duplicate primary keys when using import_from_iterable?

Best regards
Niklaus

**Comment by wildraid** [comment]
@kst83 , i think the easiest way to do this is to import into staging table first. And apply DISTINCT on Exasol side afterwards. It's normally much faster than sorting anything in Python.

```
C.set_autocommit(False)
C.execute("CREATE OR REPLACE TABLE staging_my_table LIKE my_table")
C.import_from_iterable(src, 'staging_my_table')

C.execute('INSERT INTO my_table SELECT DISTINCT * FROM staging_my_table')
C.commit()
```

**Comment by wildraid** [comment]
@kst83 , alternatively, for PRIMARY KEY column you may do this:

```
C.import_from_iterable(src, 'my_table')
C.execute('''
DELETE FROM my_table
WHERE rowid IN (
	SELECT rowid
	FROM (
		SELECT rowid, ROW_NUMBER() OVER (PARTITION BY <primary_key> ORDER BY <ts_col> DESC) AS row_number WITH INVALID PRIMARY KEY (<primary_key>)
		FROM my_table
	) a
	WHERE row_number>1
);
''')
```

It finds rows with duplicate PRIMARY KEY values, keeps the row with latest <ts_col> and deletes all other duplicate rows.

**Comment by wildraid** [comment]
@kst83 , one of my colleaguse suggested a pure Python solution for small lists.

```
my_list = [(2006, "White Pony", 3490349),(2006, "White Pony", 9492423),(2009, "White Pony", 4342342),(2006, "Red Pony", 3490349),(2006, "White Swan", 9492423),(2009, "White Swan", 4342342)]

seen = set() #< keep track of what we have seen as we go
unique_list = [x for x in my_list if not (x[1] in seen or seen.add(x[1]))]

print unique_list
# [(2006, 'White Pony', 3490349), (2006, 'Red Pony', 3490349), (2006, 'White Swan', 9492423)]
```
Credits: https://stackoverflow.com/questions/31482286/semi-unique-tuples-in-python-aka-tuple-primary-keys

Of course, it may run out of memory and much slower than any Exasol-based solution. But it should be fine for small lists less than 10k rows.

**Comment by wildraid** [comment]
I guess, we may close this issue.
