### ISSUE TITLE
export to pandas with chunksize

### ISSUE THREAD

**Issue by qlew** [badoo/pyexasol#19]
I found an issue when passing `chunksize` as callback parameter to `export_to_pandas`
```python
import pyexasol
import pandas
```
<details><summary>Output of pandas.show_versions()</summary>
<p>

 
#### INSTALLED VERSIONS
------------------
commit: None
python: 3.6.4.final.0
python-bits: 64
OS: Linux
OS-release: 4.10.0-42-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.22.0
pytest: 3.7.1
pip: 19.0.1
setuptools: 39.0.1
Cython: 0.27.3
numpy: 1.14.0
scipy: 1.0.0
pyarrow: None
xarray: None
IPython: 6.2.1
sphinx: 1.6.6
patsy: 0.5.0
dateutil: 2.6.1
pytz: 2017.3
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.4
feather: None
matplotlib: 2.1.2
openpyxl: 2.4.10
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.2
lxml: 4.1.1
bs4: 4.6.0
html5lib: 0.9999999
sqlalchemy: 1.2.1
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</p>
</details>

```python
conn = pyexasol.connect_local_config('my_exasol')
# create dummy data on DB
conn.open_schema('abt_ds')
conn.execute("delete from test")
conn.import_from_file('dummy.csv', 'TEST')
```
Exporting to pandas without chunking works as expected:
```python
query = "select * from test order by id"
df = conn.export_to_pandas(query)
print(df)
```
```bash
   ID  START_DATE
0   1  2018-11-19
1   2  2018-01-10
2   3  2017-07-26
3   4  2018-08-26
```
With chunking, `pandas` returns a `TextFileReader` (as expected)
```python
cb_params = {'chunksize': 2}
df_chunks = conn.export_to_pandas(query, callback_params=cb_params)
type(df_chunks)
```
```bash
pandas.io.parsers.TextFileReader
```
However, iterating results in an error:
```python
for chunk in df_chunks:
    print(chunk)
```
<details><summary>Output</summary>
<p>

#### 
```bash
   ID  START_DATE
0   1  2018-11-19
1   2  2018-01-10
   ID  START_DATE
2   3  2017-07-26
3   4  2018-08-26
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-38-c7f26f9d1458> in <module>()
----> 1 for chunk in df_chunks:
      2     print(chunk)

~/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py in __next__(self)
   1040     def __next__(self):
   1041         try:
-> 1042             return self.get_chunk()
   1043         except StopIteration:
   1044             self.close()

~/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py in get_chunk(self, size)
   1104                 raise StopIteration
   1105             size = min(size, self.nrows - self._currow)
-> 1106         return self.read(nrows=size)
   1107 
   1108 

~/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py in read(self, nrows)
   1067                 raise ValueError('skipfooter not supported for iteration')
   1068 
-> 1069         ret = self._engine.read(nrows)
   1070 
   1071         if self.options.get('as_recarray'):

~/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py in read(self, nrows)
   1837     def read(self, nrows=None):
   1838         try:
-> 1839             data = self._reader.read(nrows)
   1840         except StopIteration:
   1841             if self._first_chunk:

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader.read()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._read_low_memory()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._read_rows()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._tokenize_rows()

pandas/_libs/parsers.pyx in pandas._libs.parsers.raise_parser_error()

ValueError: I/O operation on closed file
```
</p>
</details>

My impression is that under the hood `pandas.read_csv` receives an open pipe, however this pipe is closed before the output of `pandas.read_csv` is returned to the caller of `ExaConnection.export_to_pandas`.

Actually, you can reproduce this type of error with `pandas` alone:
```python
# good
with open('dummy2.csv') as file:
    my_df = pandas.read_csv(file, chunksize=2)
    for chunk in my_df:
        print(chunk)
```
```bash
   ID        DATE
0   1  2018-11-19
1   2  2018-01-10
   ID        DATE
2   3  2017-07-26
3   4  2018-08-26
```
```python
# bad
with open('dummy2.csv') as file:
    my_df = pandas.read_csv(file, chunksize=2)
for chunk in my_df:
    print(chunk)
```

<details><summary>Output</summary>
<p>

#### 
```bash
   ID        DATE
0   1  2018-11-19
1   2  2018-01-10
   ID        DATE
2   3  2017-07-26
3   4  2018-08-26
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-57-ce497a3f68b5> in <module>()
      2 with open('dummy2.csv') as file:
      3     my_df = pandas.read_csv(file, chunksize=2)
----> 4 for chunk in my_df:
      5     print(chunk)

~/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py in __next__(self)
   1040     def __next__(self):
   1041         try:
-> 1042             return self.get_chunk()
   1043         except StopIteration:
   1044             self.close()

~/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py in get_chunk(self, size)
   1104                 raise StopIteration
   1105             size = min(size, self.nrows - self._currow)
-> 1106         return self.read(nrows=size)
   1107 
   1108 

~/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py in read(self, nrows)
   1067                 raise ValueError('skipfooter not supported for iteration')
   1068 
-> 1069         ret = self._engine.read(nrows)
   1070 
   1071         if self.options.get('as_recarray'):

~/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py in read(self, nrows)
   1837     def read(self, nrows=None):
   1838         try:
-> 1839             data = self._reader.read(nrows)
   1840         except StopIteration:
   1841             if self._first_chunk:

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader.read()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._read_low_memory()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._read_rows()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._tokenize_rows()

pandas/_libs/parsers.pyx in pandas._libs.parsers.raise_parser_error()

ValueError: I/O operation on closed file.
```
</p>
</details>

**Comment by wildraid** [comment]
Thank you for raising this issue.

It is an expected behaviour. The EXPORT process has to be finished by the end of `.export_to_pandas` call, and all pipes should be closed. Otherwise your query might get stuck, and you won't be able to run other queries until you finish reading. You might also experience some weird issues with threading.

But you can still do this using slightly different approach.

### Option 1: Wrap logic in `.export_to_callback` instead

You may define your own callback function. It receives raw pipe opened in binary mode, and you can do pretty much anything with it. For example, you may set `chunksize`, load data in chunks and do the processing right inside the same function.

This is the standard callback for `export_to_pandas`. Feel free to extend it:
```
def export_to_pandas(pipe, dst, **kwargs):
    import pandas
    return pandas.read_csv(pipe, skip_blank_lines=False, **kwargs)
```

Other examples: https://github.com/badoo/pyexasol/blob/master/pyexasol/callback.py

Please note that performance of this approach will be limited by 1 CPU core switching between CSV parsing and data processing.

### Option 2: Consider parallel HTTP transport

If you can split your dataset on multiple chunks and process it independently, [parallel HTTP transport](https://github.com/badoo/pyexasol/blob/master/docs/HTTP_TRANSPORT_PARALLEL.md) is the best option.

Unlike option 1, this feature scales linearly and runs on any number of CPU cores or even multiple servers. The more data you have, the bigger difference you may expect.

**Comment by qlew** [comment]
Thank you for your quick reply.

> It is an expected behaviour. EXPORT process has to be finished by the end of .export_to_pandas call, and all pipes should be closed. Otherwise your query might get stuck, and you won't be able to run other queries until you finish reading

I see. At first I was just confused: as you could pass `callback_params` to `.export_to_pandas` as standard keyword arguments for `pandas.read_csv`, I expected it to work out of box for ``chunksize``. But of course, it makes perfect sense what you say.

I haven't looked into your option 2 yet, might do so in the future. For the time being we will just wrap our processing in a callback and pass it to `export_to_callback` as you suggested. I guess for big data sets your suggestion is more efficient than using standard fetching like
```python
result = conn.execute(query)
def my_iterator(result, chunksize):
    while True:
         chunk = result.fetchmany(chunksize)
         if not chunk:
              break
         else:
             yield pandas.DataFrame.from_dict(chunk)
```
and then process each chunk:
```python
for chunk in my_iterator(result, chunksize=10000):
    process(chunk)
```
Anyhow, thanks again for your help and for your great job with PyEXASOL.
