### ISSUE TITLE
Insert statement for meta data ok?

### ISSUE THREAD

**Issue by kst83** [badoo/pyexasol#22]
I understand that when working with lots of data it makes sense to not use single insert statements but import_/export_ statements.
But is it ok to execute the insert statement for managing master data with pyexasol sind import_from_iterable doesn't seem to be flexible enough?
Or should a different library like pyodbc be used in this case?

**Comment by wildraid** [comment]
It is usually a good idea to run a tiny MySQL / PostgreSQL instance and store meta data there. It is especially true for statuses of ETL processes.

You may run some small inserts and updates, and it will be fine at first. But things tend to grow, and you'll start hitting various issues very soon. For example:

1. 100 parallel queries limit;
2. locking issues, transaction isolation is too strong;
4. big queries receiving less resources than normal;
5. SQL audit logs contention with rubbish data;
6. protected and personal data potentially exposed in SQL audit logs;

It's highly sub-optimal to store meta data in Exasol, and we wanted to explicitly discourage this behaviour. At least in Badoo.

But nothing really stops you from writing raw INSERT or UPDATE query manually and execute it.
