### ISSUE TITLE
Please expose resultType property for responseData

### ISSUE THREAD

**Issue by kamal-1** [badoo/pyexasol#24]
Exasol WebSockets API returns a property called resultType in response to the Execute command. Please expose this property in pyexasol. It will help in determining whether the query returned a resultset so it can be iterated on or the query returned a rowCount.

results (object[]) => array of result objects

- resultType (string) => type of result: **"resultSet" or "rowCount"**
- rowCount (number, optional) => present if resultType is "rowCount", number of rows
- resultSet (object, optional) => present if resultType is "resultSet", result set

**Comment by wildraid** [comment]
@kamal-1 , it's available in statement object property.
```
st = C.execute('SELECT 1')
print(st.result_type)
```
Alternatively may also try to fetch results from any query and catch exception `pyexasol.ExaRuntimeError` for queries without result sets.

**Comment by kamal-1** [comment]
Thanks @wildraid, I tried it and it works as expected.
