### ISSUE TITLE
How can I show all the tables in a specific scheme?

### ISSUE THREAD

**Issue by Ericonaldo** [badoo/pyexasol#26]
How to show all the tables in a specific scheme?
Say that I have a database called PSG, I can excecute "select * from PSG.sometable" but I can not get how many and the name of all the tables, even if I have tried many grammar and read many docs

**Comment by wildraid** [comment]
Try this call:
```
tables = C.ext.get_sys_tables()
printer.pprint(tables)
```
From this example: https://github.com/badoo/pyexasol/blob/master/examples/13_ext.py#L24-L25

"SYS" means select for system views.

**Comment by wildraid** [comment]
Hi @Ericonaldo , did it help? :)
