### ISSUE TITLE
Allow ENCODING parameter in ExaSQLImportThread

### ISSUE THREAD

**Issue by vinlopez** [badoo/pyexasol#28]
Hi,

Currently, encoding is not part of the parameters that are accepted by ExaSQLImportThread.
In our configuration, not having "ENCODING = 'UTF-8' " with cause the export to fail.

Could you please add this feature; useful and straightforward :) ?

**Comment by wildraid** [comment]
`ENCODING` in IMPORT / EXPORT statements is a bit awkward, since it does not support encodings like UTF-16.

But it's easy to add this parameter, no problem. Please check version `0.6.1`. New import / export parameter is called `encoding`.

**Comment by vinlopez** [comment]
Thanks for the super quick commit, it seems it be working like a charm!
