### ISSUE TITLE
Encryption doesn't happen on Connection

### ISSUE THREAD

**Issue by kamal-1** [badoo/pyexasol#30]
I installed pyexasol as described in "pyexasol/docs/ENCRYPTION.md". After initiating the connection to database with "encryption=True" option or specifying "encryption = True" in the config file, it still created a non-encrypted connection.

I am checking the encryption status in the exa_user_sessions system table.

Am I missing something here?

**Comment by wildraid** [comment]
This is a bug in Exasol system view, which will be fixed soon.
Connection is actually encrypted.

**Comment by wildraid** [comment]
You may double-check it by connection URL starting with "wss://" and by looking at traffic with any sniffer.

**Comment by kamal-1** [comment]
Thanks @wildraid! Do you know the version the fix is being targeted for?

**Comment by wildraid** [comment]
@kamal-1 , please track track this ticket: https://www.exasol.com/support/browse/EXASOL-2507

**Comment by kamal-1** [comment]
> @kamal-1 , please track track this ticket: https://www.exasol.com/support/browse/EXASOL-2507

Thanks!
