### ISSUE TITLE
Performance of import_from_pandas for small data frames

### ISSUE THREAD

**Issue by tkilias** [badoo/pyexasol#33]
Hello @wildraid,

I got a report, that the function import_from_pandas for small data frames (less than 100 rows) is compared with larger data frames quite slow.

I wrote a small test script and measured the performance of different data frame sizes and for very small data frames the overhead is quite large. You can find the script and results [here](
https://gist.github.com/tkilias/20e8dbb8f6f0e045b205cc92916cf71c)

In the specific use case the data frame size is given by external factors and can't be changed and might fluctuate between very small and very large. So the question is, if we might want to optimize the import_from_pandas function for different sizes. For large data frames the import via CSV is the best way, for smaller data frames insert statements or prepared statements might offer a better performance. I checked the documentation of the websocket-api of the ExasolDB and it provides an [API for PreparedStatements](https://github.com/exasol/websocket-api/blob/master/WebsocketAPI.md#createpreparedstatement-creates-a-prepared-statement) were you add the tuples to JSON of the requests.

What do you think about this? Do you have other ideas?

Thanks,
tkilias

**Comment by wildraid** [comment]
Hi @tkilias , 

Thanks you for research and performance tests. In fact, it was an intentional design decision.

1. Standard INSERT statement may potentially expose sensitive data in SQL text. It is also subject for 2M characters query size limit.

2. Prepared INSERT statement assumes all placeholders datatypes as VARCHAR(2000000), which leads to various problems. Also, prepared statements were subject for multiple bugs discovered and (hopefully) fixed in versions 6.0~6.1. It does not look very stable to me.

3. It is much more common to import large amounts of data rather than small amounts of data. If we give users two different ways of importing data, it is very likely they'll use INSERT for large amounts of data and reduce performance when it really matters. With current approach they cannot make this mistake.

4. For small amounts of data performance difference is relatively small. Users should never have "1000 iterations with 1 row" in their application. If they do, it's a bad design and it needs to be replaced with "1 iteration of 1000 rows".

Generally speaking, columnar stores always benefit from smaller amount of larger transactions.

Hope it helps!

**Comment by tkilias** [comment]
Hi @wildraid,

thanks for the reply.

Normally, I would agree with you that you should try to actual batch the data before the import, but sometimes you don't have this control over the application.

You are right, that standard INSERT might be harmful, not only exposing data, but it also might cause SQL Injections. I used the normal INSERT in the experiments only as a kind of baseline to determine the overhead of the import. 

I know that the common use case is the import of large data. My idea was actually, that we switch in the import_from_pandas function between CSV import and probably PreparedStatements depending on the data frame size. However, you said you had issues with the PreparedStatements in the past, can you give me a hint, what it actually was and I will discuss it with my colleagues what their status is.

**Comment by wildraid** [comment]
Some examples of bugs and problems related to prepared statements:

- https://www.exasol.com/support/browse/EXASOL-2515
- https://www.exasol.com/support/browse/EXASOL-2492
- https://www.exasol.com/support/browse/EXASOL-1863
- https://www.exasol.com/support/browse/EXASOL-2213
- https://www.exasol.com/support/browse/EXASOL-2296
- https://www.exasol.com/support/browse/EXASOL-2316

The implementation of this feature in Exasol looks a bit dangerous to me. At the same time IMPORT is very stable from my experience.

Also, we cannot just automatically and silently swap `import_from_pandas` with prepared statement depending on the size of dataset because this function accepts extra arguments with parameters for `to_csv()` and import parameters.

**Comment by tkilias** [comment]
Thanks, I am going to look into tickets.

You are right, import_from_pandas accepts further parameter. I am using them typically not, so I forgot of them. Hm, yeah that makes it not so easy to change the function. I need to think about it more.

**Comment by tkilias** [comment]
Hi @wildraid,

I took a look at the tickets you mentioned and discussed it with my colleagues. You are right, that in the past there were a few problems with the Prepared Statements and that some edge case there are still some problems. However, overall they are quite stable.
I would suggest the following. I am going to develop a solution in a fork. Afterwards we thoroughly test it and you can decide, if you want to integrate into the official pyexasol.

What do you think about this approach?

**Comment by wildraid** [comment]
@tkilias , I suggest to start with performance tests. You may call WebSocket API methods directly with `.req()` function.

Please make sure to:
1) test on some realistic and diverse data, not just small numbers;
2) test using real network connection within the same datacenter or cloud provider region;
3) not test on Exasol running on local laptop, since you'll have no networking overhead;
4) not test on wifi from local laptop, because wifi will be a bottleneck;

JSON serialisation overhead is quite high for larger datasets. I expect prepared statements to perform worse starting from as little as 3-5 chunks of data.

Also, in Badoo we highly discourage single-row inserts, updates and deletes in Exasol. Some people actually try to use Exasol instead of row-based DBMS (like MySQL) to hold job statuses and some meta-information. It ends up being a huge waste of resources and money and never passes the code review.

**Comment by tkilias** [comment]
Yes, this sounds reasonable for me and saves a huge time investment, if there is actually no performance benefit.

I agree single row inserts are not really a use case for an analytical database and should be the absolute exception.

**Comment by tkilias** [comment]
I started with a really naive test to get familiar with the API and added it to the examples in the following branch: https://github.com/tkilias/pyexasol/tree/feature/33_prepared_statements
On my local machine was the break even point for insert at around 10000 rows compared to import_from_pandas. I am going to extend the test later to more real world test data and run it in a proper environment.

**Comment by wildraid** [comment]
@tkilias , I've just noticed another interesting fact about inserts via prepared statements.

It appears that user cannot insert very large amounts of data this way because it's not possible to send data using multiple chunks. It is possible to read data in chunks via "fetch" call, but not write.

So weird.. :)

**Comment by wildraid** [comment]
@tkilias , in the meantime, I've tried to look into overhead of HTTP transport.

It appears that ~100-200ms is being spent on forking and running HTTP server process and transferring the "proxy string" back to parent process. Maybe we can win about ~50ms here by improving the communication mechanism and dropping some unnecessary checks from TCP server, if possible.

But this stuff is quite advanced and might have an impact on OS Windows support or might break after updates in base TCP Server.

**Comment by tkilias** [comment]
Cool, that you look into the HTTP Transport. Yeah, forking and inter process communication can be quite expensive. And you are right, efficient inter process communication gets easily very OS dependent.  

Do I understand it correct, that the size restriction for prepared statements only applies per command we send to the database. I think, we can solve this problem by reusing the prepared statement for several executePreparedStatement commands, each with a chunk of the data. I wanted to test this case anyway, because this is what users might actually try.

**Comment by wildraid** [comment]
@tkilias , I think you can possibly run `executePreparedStatement` multiple times, but it will be treated as separate statements, leading to reduced write / compression efficiency.

But maybe it's not too bad with `autocommit=False`. Let's try to test, if you have time. :)

Thank you.

**Comment by tkilias** [comment]
@wildraid Some updates from my sides. I extended the example a bit to measure a few more things:
- executePreparedStatement multiple times with autocommit off
- impact of json library
- local (docker-db) vs cloud (DB and Query Runner instance in the same region)

![chart_local_runtime](https://user-images.githubusercontent.com/5796845/66644241-ba498600-ec20-11e9-8a5a-d2c6fd0ba2f8.png)
![chart_cloud_runtime](https://user-images.githubusercontent.com/5796845/66644242-ba498600-ec20-11e9-84df-ec79e7685241.png)

**Comment by wildraid** [comment]
@tkilias , okay I think I finally managed to find the main source of ~300-700ms slowdown during HTTP transport startup. It is directly related to startup cost of Python interpreter iteself.

Starting HTTP server and sending proxy string takes only 50ms.

In theory, I can try to go back to `multiprocessing` module to take advantage of `os.fork()` call. It is very fast, but will lead to implicit copy of all resources in the new process, including WebSocket connection to Exasol and everything user opened in their application.

Need to think about it. Interesting stuff indeed.

**Comment by wildraid** [comment]
@tkilias , please try to re-run tests for `.import_from_pandas()` using version `0.9.0`.

Overhead of starting HTTP server should be reduced to ~100ms:

- 20ms for starting Python itself;
- 40ms for required imports;
- 40ms for connecting to Exasol, getting proxy string and sending it to parent process;

**Comment by tkilias** [comment]
@wildraid Yes, the python interpreter needs its time for startup. `multiprocessing` might help, but you are right this shared state might be dangerous. Can the forked process run something which disturbes the existing socket to the exasol?

I run the tests again and prepared a comparison between both version.  For the time being, I measured only locally, but we saw that the difference to the cloud setup was not too large.

![chart_local_compare_runtime](https://user-images.githubusercontent.com/5796845/67106652-52b8ab00-f1cb-11e9-974c-8ef2c6a60ca4.png)

Observations:
- `import_from_pandas` Version 0.9 got faster:

diff in seconds (0.8->0.9) | size | comment
-- | -- | --
-0.189840613697016 | 1 |
-0.129112896608421 | 10 |
-0.151784054198652 | 100 |
-0.130814204504714 | 1000 |
-0.135298765408515 | 10000 |
-0.02321814610332 | 100000 |
0.11596450090583 | 1000000 | <- not sure why this got slower, because I actually use the average of 10 runs, but might be either way a measurement artifact

- The break even point between `import_from_pandas` and prepared statements didn't move much, but the difference for 100000 rows got smaller. For smaller datasets, the prepared statements are still clearly faster.

All timings:

[timings_prepared_statements_pyexasol.zip](https://github.com/badoo/pyexasol/files/3744585/timings_prepared_statements_pyexasol.zip)

**Comment by wildraid** [comment]
Ok, let's do this. :) I'll think about various implementation details and add this function to `.ext` submodule next week.

**Comment by wildraid** [comment]
@tkilias , please check version `0.9.1`.

Function `.ext.insert_multi()`.

Example: https://github.com/badoo/pyexasol/blob/master/examples/32_insert_multi.py

It's not documented yet, so we can still change implementation details if necessary.

**Comment by tkilias** [comment]
Cool, I will check it out.

**Comment by tkilias** [comment]
@wildraid The first thing, that came to my mind for the insert_multi function was a batch size parameter, but then I saw, you mentioned in the documentation that this function should be only used for 10k or less rows. In that case, no batch size is necessary. 
What I missed in the function documentation was what format you expect for the data. From the implementation of ExaStatament.execute_prepared, I would assume iterable of rows.
Next, I will add insert_multi to the benchmark and run it again.

**Comment by wildraid** [comment]
@tkilias , argument is essentially the same as for `.import_from_iterable()`, but:

- We need at least 1 row for INSERT dataset. IMPORT can work with 0 rows.
- Iterator can be passed as valid "data" argument, but it is executed and converted into `list()` immediately. This is done on purpose in order to prevent people from inserting very large datasets using this method. Also, full materialisation is necessary anyway during creation of JSON object.
- `chunk_size` is not supported due to the same reasons. If developer finds himself in need of `chunk_size`, he should definitely use IMPORT.

**Comment by tkilias** [comment]
@wildraid:  I agree with the second and third point, it prevents misuse and that is good. The third point came only to my mind, because I had it my measurements, but for the intended sizes it is not necessary.  

However, I don't fully understand the first point.  I know that the current implementation needs at least 1 row, but would it hurt, if we add a check for this case and do nothing if 0 rows were given as parameter?

Unfortunately, I didn't found time last week, to measure the performance of your current implementation of the prepared statements, but I have it on my plan for this week. I also thought about, to extend by a concurrent load test.

**Comment by tkilias** [comment]
@wildraid Another thing, which came into my mind, currently you convert the data from rows to columns. For pandas, I actually need to do the convert from columns to rows prior to the call of _insert_multi_. Would it make sense, to have a flag for the execute_prepared method to switch in which format we expect the data. This might overhead through unnecessary conversion. However, the default behavior should be rows, as it is now, because it is probably what users expect.

**Comment by wildraid** [comment]
@tkilias , that's a good point.

Do you think the columnar format of `data` might be useful outside of artificial tests? Do you have any real use-cases? I never encountered this in practice. :)

For small amounts of data row-based format is convenient. And for large amounts of data row-based format can be easily sliced and processed in memory efficient manner.

If we work with large data frames, it's much better to use `.import_from_pandas()`, `.export_to_pandas()`, and skip Python slow data structures altogether.

**Comment by tkilias** [comment]
@wildraid I got this idea mainly from the thinking about, how do I get the pandas data frame into an iterator of tuples, because typical the table is column-wise stored in the data frame.

In general, your right for small amounts of data is probably not so important, but if the data is actually already in columnar format, why not use it.

**Comment by wildraid** [comment]
@tkilias , if user already has DataFrame which is stored in columnar format, `.import_from_pandas()` should be the best choice.

Converting efficient DataFrames into less efficient Python structures should not be encouraged, even if it saves ~10-30ms.

**Comment by wildraid** [comment]
@tkilias , I did some checks.

It looks like you can convert dataframe to small list of lists using following command:
```
df.values.tolist()
```

I did some checks, and it seems that overhead of converting data into list and back to columns is relatively small for 10.000 rows, comparing to JSON encoding and communication overhead.

About Arrow. It would be awesome if Exasol could IMPORT / EXPORT directly into ARROW format. I opened an IDEA ticket for that a while ago: https://www.exasol.com/support/browse/IDEA-418

At this point conversion to standard Python datatypes before JSON encoding eliminates all performance / efficiency benefits of Arrow. If you have data in "arrow", it's more efficient to convert it into pandas DataFrame first, and than run `.import_from_pandas()`.

I think I understand your concerns in general, but I am still not sure if it's a "good practice" to encourage users to use pseudo-columnar format using Python data structures.

And if it's a native columnar format, like "Arrow", it definitely deserves it's own optimised IMPORT / EXPORT routines.

**Comment by tkilias** [comment]
@wildraid, yesterday, I did some measurements as well, the transformation from a data frame to tuples, only adds around 1% overhead and this is for <10k rows still faster as import_from_pandas. 

Regarding the Arrow IMPORT/EXPORT, I had the same idea. Would be probably more efficient than CSV or JSON. I will keep it in mind, but can't promise anything.

**Comment by wildraid** [comment]
@tkilias , by the way, is standard IMPORT / EXPORT implemented in Java? If so, maybe Exasol could open source it and make it possible to extend this code?

Alternatively, I would love to see faster UDF transport you was working on. In this case we could implement our own custom IMPORT / EXPORT to ARROW format without too much effort.

**Comment by tkilias** [comment]
The first question, I actually can't answer, because I didn't look into the IMPORT/EXPORT. I am still working on the UDFs and yes if we get them faster, we can try to implement it with them.

**Comment by wildraid** [comment]
@tkilias , this blog post might be interesting for you:
https://arrow.apache.org/blog/2019/10/13/introducing-arrow-flight/

Arrow is about to get an optimised framework for data transport. It looks pretty good on paper.

**Comment by tkilias** [comment]
Hi @wildraid,
yes, I think, I read this article a while ago, or at least a similar one. Indeed, quite interesting.

To our original topic, I think the implementation should work, we can leave the interface for the insert_multi function as is. However, it might be a good idea to mention somewhere how to convert columns into rows and that it only introduces a small overhead.

**Comment by tkilias** [comment]
I looked up, to what I needed to set the socket_timeout. I used socket_timeout=100 for creating the connection.

**Comment by wildraid** [comment]
It's okay, I'll add it to manual once I get back to the UK in early December.

Socket timeout problem is a bit odd. It might worth fixing Exasol Connection Server. It should at least accept the connections if it's live.

**Comment by wildraid** [comment]
@tkilias , please check latest documentation updated.
https://github.com/badoo/pyexasol/blob/master/docs/REFERENCE.md#insert_multi

Cheers!
