### ISSUE TITLE
DELETE and UPDATE Statements throw an error

### ISSUE THREAD

**Issue by lumarino** [badoo/pyexasol#34]
Hey,

Is there a way to execute Delete and Update Statements?
Executing a query like: "UPDATE SCHEMA.TABLE SET SUBS= 1 WHERE USER_ID = 2"
throws the error: unexpected UPDATE.

Thanks in advance,
Luca

**Comment by wildraid** [comment]
Could you please set an option `debug=True` for `pyexasol.connect()` and paste the output here? It will look like multiple human-readable JSON requests and responses.

Thank you.

**Comment by lumarino** [comment]
Thanks for your quick answer,

i set debug to True and was able to resolve the Issue by myself,
the library was not part of the problem i just implemented it wrong.
Sorry for the unnecessary Issue, will set it to close.

have a good one,
Luca
