### ISSUE TITLE
WebSocketConnectionClosedException: Connection is already closed.

### ISSUE THREAD

**Issue by sgrjack2** [badoo/pyexasol#36]
Hi,

I am trying to make a connection with Exasol to pull some data into a dataframe, however, when I attempt to establish a connection I get an error:

WebSocketConnectionClosedException: Connection is already closed.

Which then is followed by the error ExaConnectionFailedError.

The information provided to open exasol is correct as it works when logging directly into exasol. Has anyone had any similar issues?

Thanks,
Ryan

**Comment by sgrjack2** [comment]
Yes of course. The code is basically the example shown:

> import pyexasol
> 
> C = pyexasol.connect(dsn='host:port', user='sys', password='exasol')

Where the host, port, user and password all work connecting to exasol directly.  The log is:

2019-10-08 08:18:27.961 Connection attempt [host:port]
2019-10-08 08:18:27.991 Failed to connect [host:port]

Sorry I am not allowed to publish the host/port, hopefully this will not be a problem. Could a firewall be blocking the websocket connection?

Thanks,
Ryan

**Comment by wildraid** [comment]
It could be a firewall, yes.

Can you connect from the same machine using pyodbc?

**Comment by sgrjack2** [comment]
I have someone checking if the firewall is blocking the connection.

How would I use pyodbc to connect to Exasol?

**Comment by wildraid** [comment]
https://github.com/exasol/python-exasol

This package uses pyodbc internally.

**Comment by sgrjack2** [comment]
Yes, I have connected using the python-exasol package using ODBC method. Should this method also work for pyexasol?

**Comment by wildraid** [comment]
That's odd. Which version of Exasol do you have? WebSocket interface is supported starting from version 6.

**Comment by wildraid** [comment]
@sgrjack2 , hello :) Any updates on this issue?

**Comment by sgrjack2** [comment]
Yes, sorry. I think it could be a version issue. I am working within a company that is using a older version of Exasol. However, it has been great being able to connect using the ODBC method. Once my company has upgraded the version of Exasol, in which they plan on soon, I will try the pyexasol package. Thank you for your help.
