### ISSUE TITLE
How to import only selected columns of csv file

### ISSUE THREAD

**Issue by kst83** [badoo/pyexasol#37]
Is there a way to import only selected columns of a csv file into exasol?
If I understand correctly, Exasol supports this using the the csv_cols block in the import statement, as described in the documentations.
But is it possible to use this feature with pyexasol?

**Comment by wildraid** [comment]
@kst83 , you may try to use `columns` parameter for import:
https://github.com/badoo/pyexasol/blob/master/examples/07_import_export.py#L140

It is translated directly into `csv_cols` in IMPORT SQL statement. It definitely works for re-ordering of columns, but I am not sure if it is possible to import less columns.

Please give it a try.

**Comment by kst83** [comment]
If I try to use the syntax described in the Exasol documentation I get the following error:
`ValueError: Value [1..30] is not a safe identifier. Please use tuple to pass schema names. Example: ('1', '')`
The code I use selects column 1 to 30:

`dbconn.import_from_file(file, 'T_IX_STAGE_TEST', import_params={'format': 'gz', 'column_separator': ',', 'skip': 1, 'columns': ['1..30']})`

**Comment by wildraid** [comment]
Ah, I see, it's about `1..30`. We generally discourage people to use this approach in favour of proper streaming schema evolution.

At this moment you may try to import file into pandas first with `pandas.read_csv()`, drop columns you do not need and import it using `.import_from_pandas()`.

You may also apply many other transformations that way.

**Comment by kst83** [comment]
What do you mean by streaming schema evolution? Is there some documentation about it?
Since the files are quite big I'd prefer to avoid unpacking and loading them locally.

**Comment by wildraid** [comment]
@kst83 , we normally use one of two approaches:

1) A small script checks structure of every file before IMPORT and dynamically generated `awk` command to output only required columns from each file and in proper order. For example:

```
zcat <file> | awk -F\\t '{print $1 "\t" $3 "\t" $2 "\t" $7 "\t" $5 "\t" $6 "\t" $4 }' | <import_process>
```

We have a tab-separated file here.

2) We also have Java UDF's on running inside Exasol, connecting to HDFS and performing schema evolution / column re-shuffling inside UDF code. It scales pretty well.

The main problem with `1..30` syntax is it's a very limited feature. You cannot change order of columns. You cannot normalise columns to specific datatypes and apply default values. The only conversions which are allowed are "number formatting" and "date formatting".

**Comment by wildraid** [comment]
I'll close this issue for now.

I do not see good reasons to implement `csv_cols` for IMPORT statement I would generally discourage using it due to:

1) Poor efficiency (the whole file is being sent over network, but only some columns are being used);
2) Low flexibility (cannot re-order columns);

It is advised to use an alternative solution.
