### ISSUE TITLE
How to handle identity/ autoincrement columns when writing to Exasol DB?

### ISSUE THREAD

**Issue by nazaretl** [badoo/pyexasol#39]
Hi guys,
stackoverflow could help me with the problem so I'm hopping you can give me an advice.

I have an Exasol table with an autoincrement primary key and want to fill this table using import_from_pandas from pyexasol.

By importing to exasol table I have to leave the RKEY out since Exasol auto increments it. But leaving rkey empty or not creating the rkey column in pandas at all doesn’t work for me.

I went through pandas.to_csv and it doesn’t seem to have an option to leave out columns when writing to csv.
A minimal exampe is below.

import pandas as pd
import pyexasol

score = pd.DataFrame(columns = ['rkey','score'])
score['score'] = list(range(10))
conn = pyexasol.connect(dsn=dsn,user=user, password=pw,compression=True)
conn.import_from_pandas(score,(schema, table))

**Comment by wildraid** [comment]
Try using `columns` parameter from `.import_from_pandas()`. You find an example here: https://github.com/badoo/pyexasol/blob/master/examples/07_import_export.py#L139

In theory, if you use this parameter and omit `rkey` column, Exasol should use default value. Let's see if IMPORT command supports this scenario.

In the worst case you may create a "staging" table without `rkey` column, insert data into this staging table and move it into production table with `rkey` column using `INSERT ... SELECT`.

**Comment by wildraid** [comment]
Please note that it's generally very bad practice to use AUTO INCREMENT in analytical databases. If you lose your data at any point and re-insert it again, rows will have different primary key values. It may cause all sorts of troubles when trying to reproduce previous results in reports.

Auto increment should be happening in row-based DBMS (MySQL, PostgreSQL, etc.). Alternatively, you may use semi-random numeric identifier with low probability of collisions.

Maybe it's worth to rework this system before it's too late :)

**Comment by wildraid** [comment]
@nazaretl , did you have any success with "columns" parameter?

I am curious, if it actually works with current Exasol version. :)

**Comment by wildraid** [comment]
@nazaretl ,

I've checked it myself. Parameter "columns" works correctly!

```
CREATE TABLE ac_test
(
	id DECIMAL(19,0) IDENTITY,
	name VARCHAR(255)
);
```

```
C = pyexasol.connect(dsn=config.dsn, user=config.user, password=config.password, schema=config.schema)
)

data = [
    ('bbb',), ('ccc',)
]

C.import_from_iterable(data, 'ac_test', import_params={'columns': ['name']})
```

Result:


ID | NAME
-- | --
1 | bbb
2 | ccc

**Comment by nazaretl** [comment]
Hi wildraid,
I'm very sorry, I totally forgot that I have raised an issue here because we deployed right after that and the issue was forgotten :) 

When I test your code, I always get an error, doesnt metter whether I use import_from_iterable() or import_from_pandas()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-33-85fd6f51fe43> in <module>()
      1 
      2 
----> 3 c.import_from_iterable(data, 'ac_test', import_params={'columns': ['name']})

TypeError: import_from_iterable() got an unexpected keyword argument 'import_params'

The only way to omit a column, that I have found, is to use the row insert 
INSERT INTO table(column1, column2,...)
VALUES (value1, value2,...);

But it's not an option when working with big data, it takes ages.

So INSERT ... SELECT is exactly what we did; its a work around but it workes pretty quicke because oparates exclusively on exasol.

PS: I understand your point 'dont yout autoincrement in the first place' but it is a big project and I don't have any influence on the data modeling

**Comment by wildraid** [comment]
@nazaretl , which version of PyEXASOL do you currently have?

```
import pyexasol
print(pyexasol.__version__)
```

`import_params` was not available from the very first version, but should be around for at least 1 year. Maybe simple update will help.

```
php install --upgrade pyexasol
```

Thank you.

**Comment by nazaretl** [comment]
oh i see
apparently we have 0.6.0
on my personal laptop the version is 0.10.0
I will request the new version! thanks a lot!
