### ISSUE TITLE
Openshift getpwuid(): uid not found

### ISSUE THREAD

**Issue by ageof** [badoo/pyexasol#44]
Hello everybody,
when I try to start my application with PyExasol on Openshift, it always crashes. The reason is that connection.py tries to 'clientOsUsername': getpass.getuser ()
access. Since the UID is random in OpenShift, this is not possible. It would be nice if you could parameterize clientOsUsername for OpenShift or another alternative.

Thank you and hope for a solution or implementation

**Comment by wildraid** [comment]
@ageof , please check version `0.11.2`.

I've added `client_os_username` connection option which you may use to specify custom username. In this case `getpass.getuser()` won't be called.

**Comment by ageof** [comment]
Thank you for implementation. 
Its works. The issue Van be close
