### ISSUE TITLE
Security Risk with Export

### ISSUE THREAD

**Issue by ageof** [badoo/pyexasol#46]
When I was just trying to issue a SQL statement with (export_to_pandas) a user who only had read rights, an error occurred. I found out that the data is written to a CSV via SQL export and then the data is collected via FTP. These extended rights, FTP and the CSV file represent a security risk. In my opinion, another variant for select statements should be selected. I would appreciate a feedback or a modification of the Select variant

**Comment by wildraid** [comment]
@ageof , `export_to_pandas` is called `export_` on purpose. It reflects the fact that internally this function uses EXPORT command to move data around.

However, please note that no files are created. Data is streamed directly from Exasol data node to client using HTTP protocol. There is no FTP involved and no intermediate files stored anywhere.

In my opinion, EXPORT permission does not introduce any extra security risks. If user has permission to run SELECT command, he or she can download all the data they need. It will be a bit slower than EXPORT, but final result will be exactly the same.

**Comment by wildraid** [comment]
I'll close the issue for now.

In my opinion, it does not impose any extra security risks compared to normal SELECT. No files are created during the process of EXPORT.
