### ISSUE TITLE
Limit of 30 websocket connections?

### ISSUE THREAD

**Issue by beepworld** [badoo/pyexasol#55]
Thank you very much for your awesome work on pyexasol.

There is a websocket connection limit of 30 in Exasol. If there are 30 open websocket connections, you can't open annother one. Do you know how to increase the Exasol websocket connection limit on the server side? If yes, an update of the docs would be helpful for everybody else running into this limit.

Thanks a lot!

**Comment by wildraid** [comment]
As far as I know, Exasol has a general limitation if 100 active sessions.

There is no limitation of 30 WebSocket connection. You may test it using the following script: https://github.com/badoo/pyexasol/blob/master/examples/s01_many_sessions.py

Please use a devel server for this test. Do not run it on production.

You may increase the amount of active session by using commandline parameter `-concurrentConnections=200`. However, this will lead to every session having less resources. The general system performance may suffer.

I suggest to discuss this change with customer support first.

Hope it helps!

**Comment by beepworld** [comment]
Thank you very much for your suggestions & help, wildraid.
