### ISSUE TITLE
Wrong parameter assert for EXPORT 

### ISSUE THREAD

**Issue by derolli1976** [badoo/pyexasol#57]
For the "DELIMIT" parameter the correct parameter value for "no delimiters" is "NEVER" rather than "NONE".
The way this is implemented in http_transport.py the paramter does not work with EXASOL 6.X

**Comment by derolli1976** [comment]
Suggestion;
Change line 124 in http_transport.py

old:
if delimit != 'AUTO' and delimit != 'ALWAYS' and delimit != 'NONE':

new:
if delimit != 'AUTO' and delimit != 'ALWAYS' and delimit != 'NEVER':

**Comment by wildraid** [comment]
Hi @derolli1976 ,

Thank you for pointing this out. Option `NEVER` is quite unsafe, so it's very rarely used in practice.

Fixed in 0.14.1. Full commit: https://github.com/badoo/pyexasol/commit/c062c7b22780109453a29d7e5150396f07a66642

Thank you.

**Comment by wildraid** [comment]
@derolli1976 , Hello,

Just a quick check. How did it go with the latest update introducing `NEVER` delimit?

Thank you.

**Comment by derolli1976** [comment]
Hey, sorry for the late reply.
The corrected parameter is working perfectly! Thanks a lot!
