### ISSUE TITLE
Question: Regarding using pyexasol in a docker environment

### ISSUE THREAD

**Issue by dev-mbusch** [badoo/pyexasol#60]
Hi there,

I don't know if this here is the right place for asking questions, but I have a potentially pretty stupid question so here it is:

If I wanted to use pyexasol in a script that runs in some docker container built from an image like I don't know maybe _python:3.9-slim-buster_ + installing pyexasol via pip would it be possible to connect to an Exasol instance? 

Or do I have to make sure and install an ODBC driver inside the container? 

Cheers for your help

**Comment by wildraid** [comment]
It should be possible. This page lists all optional dependencies: https://github.com/badoo/pyexasol/blob/master/docs/DEPENDENCIES.md

The core dependencies are implemented in pure Python: **websocket-client**, **rsa**. Some other dependencies require compilation and may raise some concerns: **pandas**, **pyopenssl**.

But if you do not need pandas or encryption, you may safely skip these dependencies.

**Comment by wildraid** [comment]
You do not need ODBC / JDBC driver. PyEXASOL uses an alternative native WebSocket protocol.

**Comment by dev-mbusch** [comment]
Thanks for your comments! I do believe though that the WebSocket protocol has to be activated on the server side for it to work. I've tried to connect to the Exasol instance at work with no ODBC/JDBC driver installed and it doesn't work. Admins haven't activated the websocket mode.

Anyway, thanks for answering my questions, appreciated!

**Comment by wildraid** [comment]
WebSocket protocol should be available starting from Exasol v6.0+. It is available by default. There is no way to activate or deactivate it explicitly.
