### ISSUE TITLE
import_from_pandas Couldn't connect to server error

### ISSUE THREAD

**Issue by kst83** [badoo/pyexasol#66]
I'm trying to import a Pandas df to a table on a Windows computer:

```
conn.import_from_pandas(
        df,
        ("MY_SCHEMA", "MY_TABLE"),
        import_params={
            "column_separator": ",",
            "line_separator": "\n",

        }
```
But for some reason this doesn't work.
The message of the ExaQueryError (ip and sessionid replaced) is:
 > ETL-5105: Following error occured while reading data from external connection [http://(myip):42100/000.csv failed after 0 bytes. [Failed to connect to (myip) port 42100: Connection refused],[7],[Couldn't connect to server]] (Session: (sessionid))

Could this be a bug in pyexasol?

**Comment by wildraid** [comment]
Let's see the full log with `debug=True`.

It might an antivirus or firewall peecking into non-encrypted connections and blocking suspicious activity. Try to disable all security and retry the sample code, just to rule out this possibility.

Thank you.

**Comment by kst83** [comment]
I'll try to set up something later.
The strange thing is that import_from_file does work... I'd have expected it to fail too if it was a firewall issue.

**Comment by wildraid** [comment]
Yes, this is real weird. There is no practical difference in HTTP transport mechanism between "import_from_file" and "import_from_pandas".

It all boils down to basic byte stream.

**Comment by kst83** [comment]
I tried reproducing this in a different context, but everything worked there... strange.
I'll reopen this if I can find a better example

**Comment by wildraid** [comment]
It is most likely related to some security software. Exasol data stream are not unecrypted by default and definitely "suspicious". :)
