### ISSUE TITLE
Why does the user need execute rights 

### ISSUE THREAD

**Issue by ageof** [badoo/pyexasol#69]
Why does the user need execute rights in your library if you only want to read data?
If there is no good reason, the  permissions should be read-only

**Comment by wildraid** [comment]
Hello,

Could you enable `debug=True` connection option and attach logs?

Generally speaking, permissions do not depend on driver. Permissions depend on users / roles / grants, but driver has no way of overriding it or requesting something new.

It is true for all types of drivers: ODBC, JDBC, Pyexasol, etc.
